{
 "title": "COS Fleet Manager SLOs",
 "tags": [ "cos-fleet-manager" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Availability | Request per second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_count{namespace=~\"managed-connectors-.*\", code=~\"2..\"}[5m])))",
     "legendFormat": "200"
    },
    {
     "expr": "(sum(rate(api_inbound_request_count{namespace=~\"managed-connectors-.*\", code=~\"4..\"}[5m])))",
     "legendFormat": "400"
    },
    {
     "expr": "(sum(rate(api_inbound_request_count{namespace=~\"managed-connectors-.*\", code=~\"5..\"}[5m])))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "SLOs",
   "type": "text",
   "description": "Calculated over the last 28 days\n\n",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": {
    "content": "Calculated over the last 28 days"
   }
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_inbound_request_duration_bucket{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_inbound_request_duration_bucket{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_inbound_request_duration_bucket{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "API Availability (95%) ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_count{namespace=~\"managed-connectors-.*\",code!~\"5..\"}[28d]))/sum(rate(api_inbound_request_duration_count{namespace=~\"managed-connectors-.*\"}[28d]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "API Latency p99 < 1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\",le=\"1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "API Latency p90 < 0.1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\",le=\"0.1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"cos-fleet-manager-metrics\",namespace=~\"managed-connectors-.*\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Connectors Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_count{code=~\"2..\", method=\"POST\", namespace=~\"managed-connectors-.*\", path=\"/api/connector_mgmt/v1/kafka_connectors\"}[5m]))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(increase(api_inbound_request_count{code=~\"2..\", method=\"DELETE\", namespace=~\"managed-connectors-.*\", path=\"/api/connector_mgmt/v1/kafka_connectors/-\"}[5m]))",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "Namespace Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(api_inbound_request_count{method=\"POST\",namespace=~\"managed-connectors-.*\",path=\"/api/connector_mgmt/v1/kafka_connector_namespaces/eval\"}[5m]))",
     "legendFormat": "created"
    }
   ]
  }
 ]
}