{
 "title": "Debezium Specific Connectors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(debezium_metrics_Connected{cluster_id=\"$cluster_id\"},namespace)"
    }
   },
   {
    "name": "connector_id",
    "label": "Connector ID",
    "query": {
     "query": "label_values(debezium_metrics_Connected{cluster_id=\"$cluster_id\", namespace=\"$namespace\"}, connector_id)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connector Type",
   "type": "stat",
   "description": "Type of Debezium Connector",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Connector ID",
   "type": "stat",
   "description": "Connector ID of the Debezium Connector",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "description": "Namespace of Debezium Connector",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Deployment ID",
   "type": "stat",
   "description": "Deployment ID of  Debezium Connector",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Debezium Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Milliseconds Behind Source",
   "type": "stat",
   "description": "The number of milliseconds between the last change event’s timestamp and the connector processing it. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}",
     "legendFormat": "Milliseconds Behind Source"
    }
   ]
  },
  {
   "title": "Snapshot Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Total Number of Events Seen",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "timeseries",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "stat",
   "description": "\t\nThe number of milliseconds since the connector has read and processed the most recent event",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Streaming Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Streaming Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}"
    }
   ]
  },
  {
   "title": "Total Number of Events Seen",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "timeseries",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop ",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "stat",
   "description": "\t\nThe number of milliseconds since the connector has read and processed the most recent event",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    }
   ]
  },
  {
   "title": "Kafka Connect Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connector Status",
   "type": "stat",
   "description": "The status of the connector. One of 'unassigned', 'running', 'paused', 'failed', or 'restarting'.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_status{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Requests in Flight",
   "type": "stat",
   "description": "The current number of in-flight requests awaiting a response",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_producer_requests_in_flight{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes Total",
   "type": "timeseries",
   "description": "The total number of outgoing bytes sent to all servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}",
     "legendFormat": "Outgoing Bytes Total"
    }
   ]
  },
  {
   "title": "Connector Task Status",
   "type": "stat",
   "description": "The task status of the connector. One of 'unassigned', 'running', 'paused', 'failed', or 'restarting'.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU Utilization for the connector\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "JVM Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Maximum JVM Memory Bytes",
   "type": "timeseries",
   "description": "Maximum JVM bytes allocated in Heap vs Nonheap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", area=\"heap\"}",
     "legendFormat": "Heap "
    },
    {
     "expr": "jvm_memory_bytes_max{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", area=\"nonheap\"}",
     "legendFormat": "Nonheap"
    }
   ]
  },
  {
   "title": "Total JVM Bytes Used",
   "type": "timeseries",
   "description": "Total JVM bytes used in Heap vs Nonheap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", area=\"heap\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "jvm_memory_bytes_used{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\", area=\"nonheap\"}",
     "legendFormat": "Nonheap"
    }
   ]
  }
 ]
}