{
 "title": "Data Plane | Cluster view",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{cluster_id=\"$cluster_id\", name=~\".*_mctr-.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors Requested (selected time)",
   "type": "bargauge",
   "description": "Total new Connectors requested vs the successful and the failure count within the selected time range.",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}) - count(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range)",
     "legendFormat": "Connectors Requested"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 1) unless cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range)",
     "legendFormat": "Successful"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 2) unless cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 3) unless cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range)",
     "legendFormat": "Immediately Deleted"
    },
    {
     "expr": "count((min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 5) unless cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range)",
     "legendFormat": "Still Provisioning"
    }
   ]
  },
  {
   "title": "Requested Connectors Types (selected time)",
   "type": "piechart",
   "description": "Count of the types of Connectors requested on the selected time range.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(cos_connector_type_id) ( cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} unless cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} offset $__range )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Successful Connectors Count (selected time)",
   "type": "stat",
   "description": "Total Connectors, CamelK Connectors vs Debezium Connectors running in the selected time range.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 1)",
     "legendFormat": "Total Connectors"
    },
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state{cos_connector_type_id!~\"debezium-.*\",cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 1)",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "count(min_over_time(cos_fleetshard_sync_connector_state{cos_connector_type_id=~\"debezium-.*\",cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 1)",
     "legendFormat": "Debezium connectors"
    }
   ]
  },
  {
   "title": "Successful Connectors Types (selected time)",
   "type": "piechart",
   "description": "Count of the types of CamelK Connectors for a specific cluster's namespace.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "count by (cos_connector_type_id) (min_over_time(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range]) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectors Availability (selected time)",
   "type": "gauge",
   "description": "The percentage of time that the Connectors are available in the selected time range. Expected SLO 99.5%",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range])) /\n( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\",cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range])) + ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\",cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"}[$__range])) OR on() vector(0) ) ) ) * 100"
    }
   ]
  },
  {
   "title": "Connectors Running / Crashing / Stopped",
   "type": "timeseries",
   "description": "CamelK/Debezium Connectors crashing vs running \n vs stopped over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} == 2)",
     "legendFormat": "Crashing"
    },
    {
     "expr": "count(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} == 1)",
     "legendFormat": "Running"
    },
    {
     "expr": "count(cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\",cos_namespace=~\"$namespace\"} == 4)",
     "legendFormat": "Stopped"
    }
   ]
  },
  { "title": "CamelK Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Exchanges Count (selected time)",
   "type": "stat",
   "description": "Total, Completed, Failed, and Currently Inflight Exchanges for all the CamelK Connectors.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_failed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range]))- sum(min_over_time(application_camel_context_exchanges_failed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Inflight Currently"
    }
   ]
  },
  {
   "title": "Exchanges Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of exchanges Processed  in the selected time range. Expected SLO 99.5%",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n( sum(max_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) )\n/\n( sum(max_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[$__range])) ) \n) * 100"
    }
   ]
  },
  {
   "title": "No. of Exchanges",
   "type": "timeseries",
   "description": "Exchanges Quantitative Information over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "CamelK Connectors",
   "type": "table",
   "description": "CamelK Connectors, their respective State, and their time since creation. Click on the Connector  ID to see that connector's detailed dashboard. Filter column using the Filter option next to the column header.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\", cos_connector_type_id!~\"debezium.*\", cos_namespace=~\"$namespace\"}"
    },
    {
     "expr": "label_replace(application_camel_context_uptime_seconds{cluster_id=\"$cluster_id\", namespace=~\"$namespace\"}, \"cos_connector_id\", \"$1\", \"connector_id\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KameletBinding Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the KameletBindings.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"KameletBinding\",cluster_id=\"$cluster_id\",exported_namespace=~\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "IntegrationKit Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the IntegrationKit.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"IntegrationKit\",cluster_id=\"$cluster_id\",exported_namespace=~\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Integration Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the Integration.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"Integration\",cluster_id=\"$cluster_id\",exported_namespace=~\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Debezium Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Debezium Event Count (selected time)",
   "type": "stat",
   "description": "Total, Filtered, and Erroneous events seen for the  Debezium Connectors",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range]))",
     "legendFormat": "Total Events Seen"
    },
    {
     "expr": "sum(max_over_time(debezium_metrics_NumberOfEventsFiltered{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_NumberOfEventsFiltered{context=\"streaming\"}[$__range]))",
     "legendFormat": "Filtered Events"
    },
    {
     "expr": "sum(max_over_time(debezium_metrics_NumberOfErroneousEvents{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_NumberOfErroneousEvents{context=\"streaming\"}[$__range]))",
     "legendFormat": "Erroneous Events"
    }
   ]
  },
  {
   "title": "Debezium Events Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of events completed in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n( sum(max_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"}[$__range])))\n/\n( sum(max_over_time(debezium_metrics_SnapshotDurationInSeconds{context=\"streaming\"}[$__range])) - sum(min_over_time(debezium_metrics_SnapshotDurationInSeconds{context=\"streaming\"}[$__range])))\n) \n* 100"
    }
   ]
  },
  {
   "title": "Number of Debezium Events",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 52 },
   "targets": [
    {
     "expr": "sum(debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\"})",
     "legendFormat": "Total Events Seen"
    }
   ]
  },
  {
   "title": "Debezium Connectors",
   "type": "table",
   "description": "Debezium connectors specifics and their respective state, Click on the Connector  ID to see that connector's detailed dashboard. Filter the column using the Filter option next to the column header.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cos_fleetshard_sync_connector_state{cluster_id=\"$cluster_id\", cos_connector_type_id=~\"debezium.*\", cos_namespace=~\"$namespace\"}"
    },
    {
     "expr": "label_replace(debezium_metrics_Connected{cluster_id=\"$cluster_id\", namespace=~\"$namespace\"}, \"cos_connector_id\", \"$1\", \"connector_id\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Debezium / Failed Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total{cluster_id=\"$cluster_id\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Network I/O Pressure",
   "type": "timeseries",
   "description": "Sum of Network packets received vs transmitted for all the Connectors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*_mctr-.*\",cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{name=~\".*_mctr-.*\",cluster_id=\"$cluster_id\",namespace=~\"$namespace\"}[10m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Vendor Memory NonHeap",
   "type": "timeseries",
   "description": "Sum of used Memory vs Committed (Non-Heap) for all the Connectors.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Vendor Memory Heap",
   "type": "timeseries",
   "description": "Sum of used Memory vs Committed (Heap) for all the Connectors.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memoryPool_usage_max_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Base Memory Heap",
   "type": "timeseries",
   "description": "Sum of Used vs Committed vs Maximum Memory for all the Connectors.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Vendor CPU",
   "type": "timeseries",
   "description": "Sum of the CPU Utilization for all the Connectors.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(vendor_cpu_systemCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "System Load Percent"
    }
   ]
  },
  {
   "title": "Base CPU",
   "type": "timeseries",
   "description": "Sum of the CPU Utilization for all the Connectors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(base_cpu_processCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=~\"$namespace\"})",
     "legendFormat": "Process Load Percent"
    }
   ]
  }
 ]
}